-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 18:14:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza` DEFAULT CHARACTER SET utf8 ;
USE `pizza` ;

-- -----------------------------------------------------
-- Table `pizza`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`Customers` (
  `customerID` INT NOT NULL,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `ccNum` INT NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `ccExpDate` DATE NULL,
  `ccv` INT NULL,
  `streetAddress` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zip` INT NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`Inventory` (
  `inventoryID` INT NOT NULL,
  `item` VARCHAR(45) NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`inventoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`Menu` (
  `menuID` INT NOT NULL,
  `Inventory_inventoryID` INT NOT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`menuID`),
  INDEX `fk_Menu_Inventory1_idx` (`Inventory_inventoryID` ASC),
  CONSTRAINT `fk_Menu_Inventory1`
    FOREIGN KEY (`Inventory_inventoryID`)
    REFERENCES `pizza`.`Inventory` (`inventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`Orders` (
  `orderID` INT NOT NULL,
  `orderDate` DATETIME NULL,
  `Customers_customerID` INT NOT NULL,
  `Menu_menuID` INT NOT NULL,
  `orderQuantity` INT NULL,
  `revenue` DOUBLE NULL,
  PRIMARY KEY (`orderID`, `Customers_customerID`, `Menu_menuID`),
  INDEX `fk_Orders_Customers1_idx` (`Customers_customerID` ASC),
  INDEX `fk_Orders_Menu1_idx` (`Menu_menuID` ASC),
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_customerID`)
    REFERENCES `pizza`.`Customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Menu1`
    FOREIGN KEY (`Menu_menuID`)
    REFERENCES `pizza`.`Menu` (`menuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
